dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
before_install:
  # - "sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable -y"
  - "sudo apt-get update -qq -y"
  - "sudo apt-get install -qq -y libgdal-dev libproj-dev libproj-dev spatialite-bin python-dev python3-dev"
env:
  - CFLAGS=-I/usr/include/gdal  
  # - DJANGO_VERSION=1.6.5
  # - DJANGO_VERSION=1.7
  # - DJANGO_VERSION=1.8.5
  # - DJANGO_VERSION=1.9.2
virtualenv:
  system_site_packages: false
install: 
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install --global-option=build_ext --global-option='-USQLITE_OMIT_LOAD_EXTENSION' pysqlite; fi
  - pip install GDAL==1.10
  - pip install -r requirements.txt
  - pip install coveralls
script:
  nosetests --with-coverage --cover-package=travisgis
after_success:
  coveralls
