sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - "sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable -y"
  - "sudo apt-get update -qq -y"
  - "sudo apt-get install -qq -y libgdal-dev gdal-bin python-gdal python-numpy build-essential git python-dev python3-dev"
env:
  # - DJANGO_VERSION=1.6.5
  # - DJANGO_VERSION=1.7
  # - DJANGO_VERSION=1.8.5
  # - DJANGO_VERSION=1.9.2
virtualenv:
  system_site_packages: false
install: 
  - wget https://pypi.python.org/packages/source/p/pysqlite/pysqlite-2.8.1.tar.gz
  - tar xzf pysqlite-2.8.1.tar.gz
  - cd pysqlite-2.8.1
  - sed -i '/SQLITE_OMIT_LOAD_EXTENSION/d' setup.cfg
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then python setup.py install; fi
  - cd ..
  - CFLAGS=-I/usr/include/gdal pip install GDAL==1.11
  - pip install -r requirements.txt
  - pip install coveralls
script:
  nosetests --with-coverage --cover-tests travisgis
after_success:
  coveralls
